name: GO Test and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      
    - name: Test
      run: go mod tidy && go test -race -v -failfast

    - name: Build
      run: go mod tidy && go clean -cache && go mod vendor && CGO_ENABLED=1 go build -race -o runner
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: sanjibdevnath/dongel-airtel
        tags: $RUNNER_OS.$GITHUB_SHA.$GITHUB_RUN_ID, $RUNNER_OS.$GITHUB_RUN_ID
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: rtCamp/action-slack-notify@v2
      name: Notifying in slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://a.slack-edge.com/80588/img/services/outgoing-webhook_128.png
        SLACK_TITLE: "Dongel-Airtel Build Completed"
        SLACK_USERNAME: GitAction-Dongel-Airtel-Build
