name: GO Test and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1
      
    - name: Test
      run: go test -race -v -failfast

    - name: Build
      run: go clean -cache && go mod vendor && CGO_ENABLED=1 go build -race -o runner
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: sanjibdevnath/dongel-airtel
        tags: $RUNNER_OS.$GITHUB_SHA.$GITHUB_RUN_ID, $RUNNER_OS.$GITHUB_RUN_ID
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
